name: Build & Publish Debug APK
on:
 push:
  branches:
   - master
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make Gradle executable
      run: chmod +x ./App/Android/app/gradlew
    - name: Build with Gradle
      run: ./App/Android/app/gradlew build
    - name: Build Debug APK
      run: ./App/Android/app/gradlew --debug assembleDebug
